# Generated by Django 4.2 on 2025-05-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_remove_booking_name_booking_details_booking_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='cus_email',
        ),
    ]
